<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXo7ZhxB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXo7ZhxB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXo7ZhxB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXo7ZhxB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXo7ZhxB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xo7ZhxB',
    'container.build_id' => '2a557c3f',
    'container.build_time' => 1716121096,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXo7ZhxB');
