<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHAhFEEx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHAhFEEx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHAhFEEx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHAhFEEx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHAhFEEx\App_KernelDevDebugContainer([
    'container.build_hash' => 'HAhFEEx',
    'container.build_id' => 'd884cf6f',
    'container.build_time' => 1715415768,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHAhFEEx');
