<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZIVKHdj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZIVKHdj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZIVKHdj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZIVKHdj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZIVKHdj\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZIVKHdj',
    'container.build_id' => '82a5e6b6',
    'container.build_time' => 1712221763,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZIVKHdj');
